FROM ubuntu:15.04
MAINTAINER Markus Huggler <markus.huggler@ecologic.ch>

RUN apt-get update && apt-get install -y curl
RUN curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | bash
RUN apt-get install gitlab-ci-multi-runner

RUN gitlab-ci-multi-runner register --non-interactive --url "https://ci.gitlab.com/" --description "Docker Runner Grails ($HOSTNAME)" --registration-token "c6f7cbe744f41df55dc1ef648a600e" --executor "docker" --docker-image ecologic/grails:2.4.4

CMD gitlab-ci-multi-runner run 
